import { createElement } from 'lwc';
import NewTradeButton from 'c/newTradeButton';

describe('c-new-trade-button', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-new-trade-button', {
            is: NewTradeButton
        });
        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});